import common
import argparse
from ytmusicapi import YTMusic
import time

def sync_to_youtube(min_confidence=0.90, limit=50, playlist_id=None, live=False, session_limit=500, session_cooldown=3600):
    conn = common.get_db_connection()
    cursor = conn.cursor()
    
    # Check for authentication
    try:
        # Expecting headers_auth.json or oauth.json in current directory
        yt = YTMusic("headers_auth.json") 
    except Exception as e:
        print("Error: Could not authenticate with YTMusic. Please ensure 'headers_auth.json' exists.")
        print("Run `ytmusicapi headers` to generate it.")
        print(f"Details: {e}")
        return

    # Create playlist if not provided
    if not playlist_id and live:
        try:
            playlist_id = yt.create_playlist("Billboard Nostalgia (2013-2017)", "Generated by Nostalgia Engine")
            print(f"Created new playlist: {playlist_id}")
        except Exception as e:
            print(f"Error creating playlist: {e}")
            return
    elif not playlist_id:
        print("Dry run: Would create playlist or use provided ID.")
        playlist_id = "DRY_RUN_PLAYLIST_ID"

    total_synced_session = 0
    
    while True:
        # Determine how many to fetch in this session block
        remaining_in_session = session_limit - total_synced_session
        if remaining_in_session <= 0:
            print(f"Session limit ({session_limit}) reached. Waiting for {session_cooldown} seconds...")
            if live:
                time.sleep(session_cooldown)
            total_synced_session = 0
            remaining_in_session = session_limit

        # Fetch candidates
        fetch_limit = min(limit, remaining_in_session)
        print(f"Selecting up to {fetch_limit} songs with confidence >= {min_confidence}...")
        
        cursor.execute("""
            SELECT song_id, norm_title, norm_artist, yt_video_id, confidence_score 
            FROM songs 
            WHERE confidence_score >= ? 
              AND sync_status != 'synced'
              AND yt_video_id IS NOT NULL
            ORDER BY confidence_score DESC
            LIMIT ?
        """, (min_confidence, fetch_limit))
        
        candidates = cursor.fetchall()
        print(f"Found {len(candidates)} candidates.")
        
        if not candidates:
            print("No more candidates found. Sync complete.")
            break
            
        video_ids = []
        songs_to_sync = []
        for song in candidates:
            print(f"Queueing: {song['norm_title']} - {song['norm_artist']} ({song['confidence_score']:.2f}) -> {song['yt_video_id']}")
            video_ids.append(song['yt_video_id'])
            songs_to_sync.append(song)
        
        if live:
            # Batch sync in chunks of 50
            batch_size = 50
            total_batches = (len(video_ids) + batch_size - 1) // batch_size
            
            for i in range(0, len(video_ids), batch_size):
                batch_ids = video_ids[i:i + batch_size]
                batch_songs = songs_to_sync[i:i + batch_size]
                current_batch = i // batch_size + 1
                
                print(f"Syncing batch {current_batch}/{total_batches} ({len(batch_ids)} songs)...")
                
                try:
                    status = yt.add_playlist_items(playlist_id, batch_ids)
                    
                    with conn:
                        for song in batch_songs:
                            conn.execute("UPDATE songs SET sync_status = 'synced' WHERE song_id = ?", (song['song_id'],))
                    print(f"Batch {current_batch} completed and DB updated.")
                    
                    total_synced_session += len(batch_ids)
                    time.sleep(random.uniform(2, 5)) 
                    
                except Exception as e:
                    print(f"Error syncing batch {current_batch}: {e}")
                    print("Stopping sync due to error.")
                    return # Exit on error
        else:
            print(f"Dry run: Would add {len(video_ids)} songs to playlist {playlist_id}.")
            total_synced_session += len(video_ids)
            
        # If we fetched fewer than requested, we are done
        if len(candidates) < fetch_limit:
            print("Processed all available candidates.")
            break

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--live", action="store_true", help="Actually perform the sync")
    parser.add_argument("--min-confidence", type=float, default=0.90, help="Minimum confidence score to sync")
    parser.add_argument("--limit", type=int, default=50, help="Max songs to fetch per db query loop")
    parser.add_argument("--playlist-id", type=str, help="Existing playlist ID to append to")
    parser.add_argument("--session-limit", type=int, default=500, help="Max songs to sync before cooldown")
    parser.add_argument("--cooldown", type=int, default=3600, help="Seconds to wait after session limit")
    
    args = parser.parse_args()
    
    sync_to_youtube(
        min_confidence=args.min_confidence, 
        limit=args.limit, 
        playlist_id=args.playlist_id, 
        live=args.live,
        session_limit=args.session_limit,
        session_cooldown=args.cooldown
    )
