import common
import argparse
from ytmusicapi import YTMusic
import time
import random
import os
import json

def sync_to_youtube(min_confidence=0.90, limit=50, playlist_id=None, live=False, session_limit=500, session_cooldown=3600):
    conn = common.get_db_connection()
    cursor = conn.cursor()
    
    # Check for authentication
    try:
        # Priority 1: OAuth (Recommended by user/docs for stability)
        if os.path.exists("oauth.json"):
            print("Authenticating with OAuth (oauth.json)...")
            yt = YTMusic("oauth.json")
            
        # Priority 2: Browser Auth (Legacy/Flaky)
        elif os.path.exists("headers_auth.json"):
            print("Authenticating with Browser Headers (headers_auth.json)...")
            
            # Attempt robust loading (Fix #1 & #2)
            import json
            with open("headers_auth.json", 'r') as f:
                auth_data = json.load(f)
                
            # Fix casing for Cookie
            if "Cookie" not in auth_data and "cookie" in auth_data:
                auth_data["Cookie"] = auth_data.pop("cookie")
                    
            # Remove poison pills
            keys_to_remove = [k for k in auth_data.keys() if k.lower() in ['authorization', 'oauth', 'oauth_token']]
            for k in keys_to_remove:
                del auth_data[k]
                
            # SUPER AGGRESSIVE CLEANUP: Only keep essential headers
            allowed_keys = ["User-Agent", "Cookie", "Accept", "Accept-Language", "x-goog-authuser", "x-origin"]
            auth_data = {k: v for k, v in auth_data.items() if k in allowed_keys}
            
            yt = YTMusic(auth=auth_data)
            
        else:
            raise FileNotFoundError("No 'oauth.json' or 'headers_auth.json' found.")

    except Exception as e:
        print("\n" + "="*60)
        print("AUTHENTICATION FAILURE")
        print("="*60)
        print(f"Error: {e}")
        print("-" * 60)
        print("RECOMMENDED FIX: Switch to OAuth (Stable & Long-term)")
        print("1. Run `uv run ytmusicapi oauth` in your terminal.")
        print("2. Follow the URL, authenticate, and paste the code.")
        print("3. This will generate 'oauth.json'.")
        print("4. Re-run this script.")
        print("="*60 + "\n")
        return

    # Create playlist if not provided
    if not playlist_id and live:
        try:
            playlist_id = yt.create_playlist("Billboard Nostalgia (2013-2017)", "Generated by Nostalgia Engine")
            print(f"Created new playlist: {playlist_id}")
        except Exception as e:
            print(f"Error creating playlist: {e}")
            return
    elif not playlist_id:
        print("Dry run: Would create playlist or use provided ID.")
        playlist_id = "DRY_RUN_PLAYLIST_ID"

    total_synced_session = 0
    
    while True:
        # Determine how many to fetch in this session block
        remaining_in_session = session_limit - total_synced_session
        if remaining_in_session <= 0:
            print(f"Session limit ({session_limit}) reached. Waiting for {session_cooldown} seconds...")
            if live:
                time.sleep(session_cooldown)
            total_synced_session = 0
            remaining_in_session = session_limit

        # Fetch candidates
        fetch_limit = min(limit, remaining_in_session)
        print(f"Selecting up to {fetch_limit} songs with confidence >= {min_confidence}...")
        
        cursor.execute("""
            SELECT song_id, norm_title, norm_artist, yt_video_id, confidence_score 
            FROM songs 
            WHERE confidence_score >= ? 
              AND sync_status != 'synced'
              AND yt_video_id IS NOT NULL
            ORDER BY confidence_score DESC
            LIMIT ?
        """, (min_confidence, fetch_limit))
        
        candidates = cursor.fetchall()
        print(f"Found {len(candidates)} candidates.")
        
        if not candidates:
            print("No more candidates found. Sync complete.")
            break
            
        video_ids = []
        songs_to_sync = []
        for song in candidates:
            print(f"Queueing: {song['norm_title']} - {song['norm_artist']} ({song['confidence_score']:.2f}) -> {song['yt_video_id']}")
            video_ids.append(song['yt_video_id'])
            songs_to_sync.append(song)
        
        if live:
            # Batch sync in chunks of 50
            batch_size = 50
            total_batches = (len(video_ids) + batch_size - 1) // batch_size
            
            for i in range(0, len(video_ids), batch_size):
                batch_ids = video_ids[i:i + batch_size]
                batch_songs = songs_to_sync[i:i + batch_size]
                current_batch = i // batch_size + 1
                
                print(f"Syncing batch {current_batch}/{total_batches} ({len(batch_ids)} songs)...")
                
                try:
                    status = yt.add_playlist_items(playlist_id, batch_ids)
                    
                    with conn:
                        for song in batch_songs:
                            conn.execute("UPDATE songs SET sync_status = 'synced' WHERE song_id = ?", (song['song_id'],))
                    print(f"Batch {current_batch} completed and DB updated.")
                    
                    total_synced_session += len(batch_ids)
                    time.sleep(random.uniform(2, 5)) 
                    
                except Exception as e:
                    print(f"Error syncing batch {current_batch}: {e}")
                    print("Stopping sync due to error.")
                    return # Exit on error
        else:
            print(f"Dry run: Would add {len(video_ids)} songs to playlist {playlist_id}.")
            break

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sync songs to YouTube Music playlist.")
    parser.add_argument("--min-confidence", type=float, default=0.90, help="Minimum confidence score to sync")
    parser.add_argument("--limit", type=int, default=50, help="Number of songs to sync per run")
    parser.add_argument("--playlist-id", type=str, help="Existing playlist ID (optional)")
    parser.add_argument("--live", action="store_true", help="Actually create/update playlist")
    
    args = parser.parse_args()
    
    sync_to_youtube(
        min_confidence=args.min_confidence, 
        limit=args.limit, 
        playlist_id=args.playlist_id,
        live=args.live
    )
